version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: weekly
    time: "02:00"
    timezone: Europe/Copenhagen
  open-pull-requests-limit: 99
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "02:00"
    timezone: Europe/Copenhagen
  open-pull-requests-limit: 99
