before_install:
  - sudo apt-get update && sudo apt-get install -y wait-for-it
rvm: true
services:
  mysql:
    environment:
      - MYSQL_USER=build
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=baza_database_manager_test
    expose:
      - 3306
    image: mysql:8.0.26
    mem_limit: 4096m
script:
  - yarn
  - cp config/database.peak_flow.yml config/database.yml
  - wait-for-it mysql:3306
  - RAILS_ENV=test bundle exec rake db:schema:load
  - RAILS_ENV=test bundle exec rake baza:db:migrate
  - bin/webpack
  - bundle exec rspec
  - bundle exec rake best_practice_project:run
