before_install:
  - gem install bundler -v 2.1.2
rvm: true
services:
  mysql:
    environment:
      - MYSQL_USER=build
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=baza_database_manager_test
    image: mysql:5.7.29
    expose:
      - 3306
script:
  - cp config/database.peak_flow.yml config/database.yml
  - RAILS_ENV=test bundle exec rake db:schema:load
  - RAILS_ENV=test bundle exec rake baza:db:migrate
  - bundle exec rspec
  - bundle exec rake best_practice_project:run
