# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a6e5cf628cc35280b0356ff3659d8c4ad0850d3fd4b3b55cf7593e908cd93cd64c46ad1a2fd529b040080f44f2d4bb0567dcbb9d31610232b5cedeb848052d33

test:
  secret_key_base: 939979c3ba0ac8970725b0f7b3e5f534ec9007508c7407a0db2ed5b682701964890486335de0b0eed50db23484301c858d70b0344982ca0ed10946c8a977aafa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
